### ISSUE TITLE
osx binary

### ISSUE THREAD

**Issue by extrawurst** [gecko0307/atrium#2]
please provide an osx version or a dub project to allow a normal person to build it :)

**Comment by sanchopanca** [comment]
Since when osx users are normal people and others are not?

**Comment by extrawurst** [comment]
by "normal" user i meant the average D user that is used to dub and not some custom build tool that only one project uses

**Comment by gecko0307** [comment]
It won't work on OSX anyway due to OpenGL issues. I haven't figured out yet what minimal set of extensions I need to load explitcitly. Currently it tries to load all extensions (default Derelict2 behaviour), and, AFAIK, there are issues with that on OSX. With dmech demos, this was easy to fix, but Atrium is mush more complex.

**Comment by gecko0307** [comment]
Seems working now.

**Comment by extrawurst** [comment]
awesome!
